language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# 테스트
# CI 실행 완료시 메일로 알람///
notifications:
  email:
    recipients:
      - sangjoahn@gscdn.com
  slack:
    rooms:
      - secure: "G7Y2RzQbfys4bUeOiawIY10VYBgCpFCXM19/aszZCKIY6IhcLOHRLEpWUOveBkY3a+uDx42QbxPwD6bv4/IBACMJUJZagrlu3MsnY/Pg3tCATzKENcHZHRYwi5JDoqX+Zv+6yny80oumASvZfiM7X+WfWyeSBa8oqDEnGDx7M3pjSx3TiGiKOLwJqWSRlOUh/sptUBcDBXjjCP8LY9VV215PfRkmXmS1+AyohFr+8gpD3z/YR+tkGrSbsXErB2J1QnCFE/WpOtsQFEaSoT/2SGE80latuXzVfBGGHOataQA23bxuYzyjYO7boz6jfuZuk0Xhf8KzU8sRM2pQATJ8EhxOdfTjCaUixc1Jx4wcUS6A2/5U/3upj+8NGUbyPTJoSKh3IPQiK0YY4BWq7pi+O5L2r4iwtl78lYqzSJBO4795r3zUFqGcVENatlsB2MH/nSel3d6LUgZBumTH61y2I2jnLd8waMwFllXgWb55++syrGXeyYYkH/f9ET4WuV92KS8NSACHAt7Y3grV8LCvz6k2ViNMKzcLsK1xpnNO9KmpiqnfgJ0LFf0MQLaSqiVmPCIhIvsY9EABGqskd5/sv3+Hlvr5JQYDvfv8ATuEmBDCL5H6X+wPM9N6jgnOAVSZJzgq+fhcjSTZyNzs57aRK+HrLdRCLa9Qq5L5X2+Mz2w="