language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람///
notifications:
  email:
    recipients:
      - sangjoahn@gscdn.com
  slack:
    rooms:
        - gsneotekdevops:Uykbh2DwZSRvbZetuC7qRDI1#test
      on_success: always  # change: send a notification when the build status changes.
      on_failure: always  # always: always send a notification.